### ISSUE TITLE
This is in the track twice

### ISSUE THREAD

**Issue by changamanda** [learn-co-curriculum/intro-to-tdd-rspec-and-learn#13]
@SophieDeBenedetto In Ruby Introduction and Variables and Methods

**Comment by SophieDeBenedetto** [comment]
this should be fixed as of yesterday. @jonas--is there something I need to do to clean this up?

**Comment by AnnJohn** [comment]
@SophieDeBenedetto  do you know if this was fixed?

**Comment by AnnJohn** [comment]
Fixed. closing issue.

**Comment by AnnJohn** [comment]
FIxed. closing issue.

**Comment by AnnJohn** [comment]
@SophieDeBenedetto Don't think this has been fixed. Could you revisit?

**Comment by SophieDeBenedetto** [comment]
removed it's second appearance.
