### ISSUE TITLE
Header delineations

### ISSUE THREAD

**Issue by faiyamTestFS32** [learn-co-curriculum/intro-to-tdd-rspec-and-learn#14]
If possible, the "Writing a Test" header should somehow look like a parent header to "Identifying the Desired Behavior". Here it looks like we just forgot to write the Writing a Test section.

![image](https://cloud.githubusercontent.com/assets/15016713/10432040/b3cf3050-70d6-11e5-98bc-75e103864ed5.png)

**Comment by AnnJohn** [comment]
This is a Learn issue- the fonts are in different markdown heading sizes in github but is not rendering properly on Learn. Closing this issue for now and can revisit when Product has time.
