### ISSUE TITLE
Haven't discussed actual git workflow, but tells users to git add/commit/push/open PR

### ISSUE THREAD

**Issue by loganhasson** [learn-co-curriculum/intro-to-tdd-rspec-and-learn#15]
```
Run learn again and you should see the test suite passing. Great job!

At this point you should stage your solution with git add . and commit it with git commit -am "Done" and push it with git push. Then open a pull request to pass this lab.
```

**Comment by PeterBell** [comment]
Hey @loganhasson looks like this was resolved by https://github.com/learn-co-curriculum/intro-to-tdd-rspec-and-learn/commit/19d4f13ca9a1a5d915650ef0505f7c09c9128174 some time after your issue, so I'm gonna close the issue as it's fixed. Thanks so much for mentioning this!
