### ISSUE TITLE
Code passed when instructions said it should have failed.

### ISSUE THREAD

**Issue by jinjo39** [learn-co-curriculum/intro-to-tdd-rspec-and-learn#18]
Instructions said to update current_age_for_birth_year.rb:

"Update the code in current_age_for_birth_year.rb to entirely read:

def current_age_for_birth_year(birth_year)
end"

But, I did this and my code passed. I did not get the error message that supposedly should have been this:

"1) current_age_for_birth_year method returns the age of a person based on the year of birth
     Failure/Error: expect(age_of_person).to eq(31)

       expected: 31
            got: nil

       (compared using ==)
     # ./spec/current_age_for_birth_year_spec.rb:6:in `block (2 levels) in <top (required)>' "

**Comment by AnnJohn** [comment]
Hi @jinjo39 so sorry for the delay with this, but it looks like you've been able to move past this lab. If this is still an issue, please use the Ask a Question tool in Learn and someone will get back to you right away. Thanks!
