### ISSUE TITLE
record video

### ISSUE THREAD

**Issue by aviflombaum** [learn-co-curriculum/intro-to-tdd-rspec-and-learn#2]

**Comment by AnnJohn** [comment]
Iceboxing for  now

**Comment by AnnJohn** [comment]
Iceboxing for now

**Comment by PeterBell** [comment]
Just adding the video label so we could put together a shooting schedule to knock a bunch of these out together if they're worth shooting

**Comment by itzsaga** [comment]
@PeterBell I just did a Study Group on this lab and recorded it. I'll add it to the Instruction app in the next couple days.

**Comment by curiositypaths** [comment]
HI @itzsaga

Thank you for recording a Study Group for this lab. Could you provide us with the link?

**Comment by itzsaga** [comment]
@curiositypaths it's in the instruction app here: http://instruction.learn.co/student/video_lectures#/179 :smiley:
