### ISSUE TITLE
TDD, RSPEC, AND LEARN trouble finding this lab

### ISSUE THREAD

**Issue by phamducv** [learn-co-curriculum/intro-to-tdd-rspec-and-learn#20]
I am having trouble finding the lab for the TDD, RSPEC, AND LEARN lesson

**Comment by AnnJohn** [comment]
Hi @phamducv you should be able to type learn open in your terminal and that should work. But for immediate help, please use the Ask a Question tool in Learn and someone from our support staff will get back to your right away. Thanks!
