### ISSUE TITLE
Unable to open Nitrous

### ISSUE THREAD

**Issue by GHart1225** [learn-co-curriculum/intro-to-tdd-rspec-and-learn#21]
Hi All, I have an error when opening nitrous - Adding Learn.co's public key to nitrous container. - How am supposed to add anything to nitrous if I can't open it?

Thanks - Greg

**Comment by AnnJohn** [comment]
Hi @GHart1225 so sorry for the delay on this. If this is still an issue, please use the Ask a Question tool in Learn and someone from our support team will help you out. Thanks!
