### ISSUE TITLE
2015 vs 2016 issue

### ISSUE THREAD

**Issue by pzhestkov** [learn-co-curriculum/intro-to-tdd-rspec-and-learn#29]
Att! to developers of the course. The current topic has an error in a year, at the end of the task. The proposed code doesn't work:
  "2016 - birth_year", use 2015 to pass it. 
The previous year has passed, apparently, didn't happen to change it in the task yet. 
Thank you.

**Comment by AnnJohn** [comment]
this should be fixed. thanks.
