### ISSUE TITLE
TDD, Rspec, and Learn

### ISSUE THREAD

**Issue by theomoji** [learn-co-curriculum/intro-to-tdd-rspec-and-learn#37]
I put in: 
require_relative '../current_age_for_birth_year.rb'
 
describe "current_age_for_birth_year method" do
  it "returns the age of a person based on the year of birth" do
    age_of_person = current_age_for_birth_year(1984)
 
    expect(age_of_person).to eq(32)
  end
end
but got the errors:
// ♥ learn                                                                                                                    
/home/gken90-40635/code/labs/intro-to-tdd-rspec-and-learn-cb-000/current_age_for_birth_year.rb:1:in `require_relative': cannot
 load such file -- /home/gken90-40635/code/labs/current_age_for_birth_year.rb (LoadError)                                     
        from /home/gken90-40635/code/labs/intro-to-tdd-rspec-and-learn-cb-000/current_age_for_birth_year.rb:1:in `<top (requir
ed)>'                                                                                                                         
        from /home/gken90-40635/code/labs/intro-to-tdd-rspec-and-learn-cb-000/spec/current_age_for_birth_year_spec.rb:1:in `re
quire_relative'                                                                                                               
        from /home/gken90-40635/code/labs/intro-to-tdd-rspec-and-learn-cb-000/spec/current_age_for_birth_year_spec.rb:1:in `<t
op (required)>'                                                                                                               
        from /usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `load'              
        from /usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `block in load_spec_
files'                                                                                                                        
        from /usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1433:in `each'              
        from /usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1433:in `load_spec_files'   
        from /usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:100:in `setup'                     
        from /usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:86:in `run'                        
        from /usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:71:in `run'                        
        from /usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:45:in `invoke'                     
        from /usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.4/exe/rspec:4:in `<top (required)>'                           
        from /usr/local/rvm/gems/ruby-2.3.1/bin/rspec:23:in `load'                                                            
        from /usr/local/rvm/gems/ruby-2.3.1/bin/rspec:23:in `<main>'                                                          
        from /usr/local/rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'                                            
        from /usr/local/rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'  

I asked the community and KevinDTran helped me out and identified that I don't need to write "require_relative "

**Comment by Joll59** [comment]
@theomoji Fantastic that you found a solution.
