### ISSUE TITLE
wrong year

### ISSUE THREAD

**Issue by CorinneKelly** [learn-co-curriculum/intro-to-tdd-rspec-and-learn#39]
Its 2017 now but the problem reflects year 2016. You should change the current year to 2017 and adjust the answer to 33

def current_age_for_birth_year(birth_year)
  2016 - birth_year
end

**Comment by Joll59** [comment]
@CorinneKelly. 
In this Lab you are assuming the year is 2016. 
The Read Me tells you as much. 
This was not an oversight, the Read Me addresses this issue towards the end.
