### ISSUE TITLE
Possible error in Spec test 

### ISSUE THREAD

**Issue by RJFerguson** [learn-co-curriculum/intro-to-tdd-rspec-and-learn#41]
```
  describe "current_age_for_birth_year method" do
    it "returns the age of a person based on the year of birth" do
      age_of_person = current_age_for_birth_year(1984)
      expect(age_of_person).to eq(32)
    end
  end

```

I think the Spec test is now wrong, 2017 - 1984 = 33. I suspect the test condition hasn't been updated to reflect the new year, but what do I know.

**Comment by Joll59** [comment]
@RJFerguson.
In this Lab you are assuming the year is 2016. 
The Read Me tells you as much. 
This was not an oversight, the Read Me addresses this issue towards the end.
