### ISSUE TITLE
test answer expects results based on 2016 even tho its now 2017

### ISSUE THREAD

**Issue by tomalley104** [learn-co-curriculum/intro-to-tdd-rspec-and-learn#42]
Tried using `Time.now.year`, but the test failed. It passed once i used `2016` instead of current year.

**Comment by Joll59** [comment]
@tomalley104.
In this Code Along you are assuming the year is 2016. 
The Read Me tells you as much. 
This was not an oversight, the Read Me addresses this issue at the end.
