### ISSUE TITLE
Testing suite still expects the current year to be 2016

### ISSUE THREAD

**Issue by CalebKnox** [learn-co-curriculum/intro-to-tdd-rspec-and-learn#48]

**Comment by Joll59** [comment]
@CalebKnox 
In this Lab you are assuming the year is 2016. 
The Read Me tells you as much.
This was not an oversight, the Read Me addresses this issue towards the end.

**Comment by Jellp** [comment]
In this lesson, they show you that using Time.now.year at the bottom would be better. I personally think it would be nice to have this updated.

**Comment by cjbrock** [comment]
@Jellp @Joll59 This lab is using an example year. We've updated it to reflect a year that isn't so close to the current year to eliminate any confusion.
