### ISSUE TITLE
No RSpec File in the lab

### ISSUE THREAD

**Issue by ashwinvidiyala** [learn-co-curriculum/intro-to-tdd-rspec-and-learn#52]
When I loaded the lab, there was no current_age_for_birth_year_spec.rb file in the spec folder. I had to create it with this command (and then I copied the code from the lesson):

touch current_age_for_birth_year_spec.rb

**Comment by gj** [comment]
Hi @ashwinvidiyala !

Looks like you got everything sorted out: https://github.com/ashwinvidiyala/intro-to-tdd-rspec-and-learn-ruby-intro-000/blob/master/spec/current_age_for_birth_year_spec.rb

🙂
