### ISSUE TITLE
Abstraction and Encapsulation Example logic is off

### ISSUE THREAD

**Issue by itzsaga** [learn-co-curriculum/intro-to-tdd-rspec-and-learn#53]
This code: `users_age = current_age_for_birth_year(birth_year) + (Time.now.year - 2003)` produces the incorrect age when puts to the console. `users_age = current_age_for_birth_year(birth_year)` will fix it. PR coming.

**Comment by curiositypaths** [comment]
Hi there,

We've updated the solution code. 

As always thank you for contributing!
