### ISSUE TITLE
the test suite won't pass if you follow the directions 

### ISSUE THREAD

**Issue by codingkasia** [learn-co-curriculum/intro-to-tdd-rspec-and-learn#56]
How do we calculate the difference between the year currently and the year provided to the method as an argument birth_year? You might simply subtract the birth year from the current year, 2003 in our case.

def current_age_for_birth_year(birth_year)
  2003 - birth_year
end
Run learn again and you should see the test suite passing. Great job!

**NOTE: we are currently in 2018 but the test will only run when you enter 2016 (unless you change the entire test code to include Time.now.year)**

**Comment by drakeltheryuujin** [comment]
Hi @codingkasia,

Thanks for your feedback. The tests and curriculum should be updated to accurately reflect what is expected to submit to get the tests passing. If you feel that the issue has not been resolved and that the curriculum still needs addressing, feel free to re-open the issue.

Keep at it! 💙
